- id: llm-code-review
  name: LLM Code Review
  description: Run Code Review by a LLM
  entry: llm-code-review
  language: python
  verbose: true
  pass_filenames: true
  additional_dependencies:
    - absl-py
    - httpx
    - langchain[google-genai]
    - langchain-ollama
    - rich
  stages:
    - pre-commit
    - pre-merge-commit
